GET http://localhost:8080/api/uzytkownicy/whoami
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YmFwcCIsInN1YiI6Im5hdWN6eWNpZWxAbG9jYWwiLCJpYXQiOjE3NTc2NDQwMjAsImV4cCI6MTc1NzY0NDkyMCwidWlkIjoyLCJyb2xhIjoiTkFVQ1pZQ0lFTCIsInR5cFRva2VudSI6IkFDQ0VTUyJ9.pBl9H-aEhgHSeKU3S69w6hkiMv7izDc2uEQi20tB96o
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2025.1.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

<> 2025-09-12T042709.500.html

###

POST http://localhost:8080/api/auth/login
Content-Type: application/json
Content-Length: 57
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2025.1.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

{ "email": "nauczyciel@local", "haslo": "nauczyciel123" }

<> 2025-09-12T042700.200.json

###

GET http://localhost:8080/api/uzytkownicy/whoami
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YmFwcCIsInN1YiI6Im5hdWN6eWNpZWxAbG9jYWwiLCJpYXQiOjE3NTc2NDMyNjgsImV4cCI6MTc1NzY0NDE2OCwidWlkIjoyLCJyb2xhIjoiTkFVQ1pZQ0lFTCIsInR5cFRva2VudSI6IkFDQ0VTUyJ9.mFS-KmrrBHoYvTFIDUPqMqddCAedfojTNkB9pz49Lfs
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2025.1.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

<> 2025-09-12T041432.500.html

###

POST http://localhost:8080/api/auth/login
Content-Type: application/json
Content-Length: 57
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2025.1.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

{ "email": "nauczyciel@local", "haslo": "nauczyciel123" }

<> 2025-09-12T041428.200.json

###

POST http://localhost:8080/api/import
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ3YmFwcCIsInN1YiI6Im5hdWN6eWNpZWxAbG9jYWwiLCJpYXQiOjE3NTc2NDExNzMsImV4cCI6MTc1NzY0MjA3MywidWlkIjoyLCJyb2xhIjoiTkFVQ1pZQ0lFTCIsInR5cFRva2VudSI6IkFDQ0VTUyJ9._At_sR-D0L0uc2CEhJRi2N6fGgXBvxCnSlzH2jCfmlc
Content-Type: application/json
Content-Length: 115
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2025.1.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

{
  "format": "JSON",
  "dane": { "tablice": [ { "tytul": "Import 1757642983", "nazwa": "Import 1757642983" } ] }
}

###

GET http://localhost:8080/api/tablice
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ3YmFwcCIsInN1YiI6Im5hdWN6eWNpZWxAbG9jYWwiLCJpYXQiOjE3NTc2NDExNzMsImV4cCI6MTc1NzY0MjA3MywidWlkIjoyLCJyb2xhIjoiTkFVQ1pZQ0lFTCIsInR5cFRva2VudSI6IkFDQ0VTUyJ9._At_sR-D0L0uc2CEhJRi2N6fGgXBvxCnSlzH2jCfmlc
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2025.1.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

###

POST http://localhost:8080/api/import
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ3YmFwcCIsInN1YiI6Im5hdWN6eWNpZWxAbG9jYWwiLCJpYXQiOjE3NTc2NDExNzMsImV4cCI6MTc1NzY0MjA3MywidWlkIjoyLCJyb2xhIjoiTkFVQ1pZQ0lFTCIsInR5cFRva2VudSI6IkFDQ0VTUyJ9._At_sR-D0L0uc2CEhJRi2N6fGgXBvxCnSlzH2jCfmlc
Content-Type: application/json
Content-Length: 131
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2025.1.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

{
  "format": "JSON",
  "dane": {
    "tablice": [
      { "tytul": "Import 1757642385", "nazwa": "Import 1757642385" }
    ]
  }
}

###

POST http://localhost:8080/api/import
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ3YmFwcCIsInN1YiI6Im5hdWN6eWNpZWxAbG9jYWwiLCJpYXQiOjE3NTc2NDExNzMsImV4cCI6MTc1NzY0MjA3MywidWlkIjoyLCJyb2xhIjoiTkFVQ1pZQ0lFTCIsInR5cFRva2VudSI6IkFDQ0VTUyJ9._At_sR-D0L0uc2CEhJRi2N6fGgXBvxCnSlzH2jCfmlc
Content-Type: application/json
Content-Length: 105
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2025.1.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

{
  "format": "json",
  "dane": { "tablice": [ { "nazwa": "Import JWT", "opis": "", "warstwy": [] } ] }
}

###

GET http://localhost:8080/api/tablice/16/export.pdf?width=1600&height=900&grid=true&step=32&email=nauczyciel@local
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ3YmFwcCIsInN1YiI6Im5hdWN6eWNpZWxAbG9jYWwiLCJpYXQiOjE3NTc2NDExNzMsImV4cCI6MTc1NzY0MjA3MywidWlkIjoyLCJyb2xhIjoiTkFVQ1pZQ0lFTCIsInR5cFRva2VudSI6IkFDQ0VTUyJ9._At_sR-D0L0uc2CEhJRi2N6fGgXBvxCnSlzH2jCfmlc
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2025.1.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

<> tablica-16.pdf

###

GET http://localhost:8080/api/tablice/16/export.png?width=1600&height=900&grid=true&step=32&email=nauczyciel@local
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ3YmFwcCIsInN1YiI6Im5hdWN6eWNpZWxAbG9jYWwiLCJpYXQiOjE3NTc2NDExNzMsImV4cCI6MTc1NzY0MjA3MywidWlkIjoyLCJyb2xhIjoiTkFVQ1pZQ0lFTCIsInR5cFRva2VudSI6IkFDQ0VTUyJ9._At_sR-D0L0uc2CEhJRi2N6fGgXBvxCnSlzH2jCfmlc
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2025.1.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

<> tablica-16.png

###

GET http://localhost:8080/api/tablice/16/export?format=JSON&email=nauczyciel@local
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ3YmFwcCIsInN1YiI6Im5hdWN6eWNpZWxAbG9jYWwiLCJpYXQiOjE3NTc2NDExNzMsImV4cCI6MTc1NzY0MjA3MywidWlkIjoyLCJyb2xhIjoiTkFVQ1pZQ0lFTCIsInR5cFRva2VudSI6IkFDQ0VTUyJ9._At_sR-D0L0uc2CEhJRi2N6fGgXBvxCnSlzH2jCfmlc
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2025.1.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

<> 2025-09-12T034905.200.json

###

GET http://localhost:8080/api/tablice/16
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ3YmFwcCIsInN1YiI6Im5hdWN6eWNpZWxAbG9jYWwiLCJpYXQiOjE3NTc2NDExNzMsImV4cCI6MTc1NzY0MjA3MywidWlkIjoyLCJyb2xhIjoiTkFVQ1pZQ0lFTCIsInR5cFRva2VudSI6IkFDQ0VTUyJ9._At_sR-D0L0uc2CEhJRi2N6fGgXBvxCnSlzH2jCfmlc
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2025.1.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

<> 2025-09-12T034820.200.json

###

POST http://localhost:8080/api/tablice
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ3YmFwcCIsInN1YiI6Im5hdWN6eWNpZWxAbG9jYWwiLCJpYXQiOjE3NTc2NDExNzMsImV4cCI6MTc1NzY0MjA3MywidWlkIjoyLCJyb2xhIjoiTkFVQ1pZQ0lFTCIsInR5cFRva2VudSI6IkFDQ0VTUyJ9._At_sR-D0L0uc2CEhJRi2N6fGgXBvxCnSlzH2jCfmlc
Content-Type: application/json
Content-Length: 50
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2025.1.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

{ "tytul": "Debug 1757641597", "wlascicielId": 2 }

<> 2025-09-12T034637.200.json

###

GET http://localhost:8080/api/tablice/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ3YmFwcCIsInN1YiI6Im5hdWN6eWNpZWxAbG9jYWwiLCJpYXQiOjE3NTc2NDExNzMsImV4cCI6MTc1NzY0MjA3MywidWlkIjoyLCJyb2xhIjoiTkFVQ1pZQ0lFTCIsInR5cFRva2VudSI6IkFDQ0VTUyJ9._At_sR-D0L0uc2CEhJRi2N6fGgXBvxCnSlzH2jCfmlc
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2025.1.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

<> 2025-09-12T034632.400.json

###

POST http://localhost:8080/api/tablice
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ3YmFwcCIsInN1YiI6Im5hdWN6eWNpZWxAbG9jYWwiLCJpYXQiOjE3NTc2NDExNzMsImV4cCI6MTc1NzY0MjA3MywidWlkIjoyLCJyb2xhIjoiTkFVQ1pZQ0lFTCIsInR5cFRva2VudSI6IkFDQ0VTUyJ9._At_sR-D0L0uc2CEhJRi2N6fGgXBvxCnSlzH2jCfmlc
Content-Type: application/json
Content-Length: 50
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2025.1.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

{ "tytul": "Debug 1757641299", "wlascicielId": 2 }

<> 2025-09-12T034139.200.json

###

GET http://localhost:8080/api/tablice/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ3YmFwcCIsInN1YiI6Im5hdWN6eWNpZWxAbG9jYWwiLCJpYXQiOjE3NTc2NDExNzMsImV4cCI6MTc1NzY0MjA3MywidWlkIjoyLCJyb2xhIjoiTkFVQ1pZQ0lFTCIsInR5cFRva2VudSI6IkFDQ0VTUyJ9._At_sR-D0L0uc2CEhJRi2N6fGgXBvxCnSlzH2jCfmlc
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2025.1.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

<> 2025-09-12T034019.400.json

###

POST http://localhost:8080/api/tablice
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ3YmFwcCIsInN1YiI6Im5hdWN6eWNpZWxAbG9jYWwiLCJpYXQiOjE3NTc2NDExNzMsImV4cCI6MTc1NzY0MjA3MywidWlkIjoyLCJyb2xhIjoiTkFVQ1pZQ0lFTCIsInR5cFRva2VudSI6IkFDQ0VTUyJ9._At_sR-D0L0uc2CEhJRi2N6fGgXBvxCnSlzH2jCfmlc
Content-Type: application/json
Content-Length: 50
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2025.1.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

{ "tytul": "Debug 1757641212", "wlascicielId": 2 }

<> 2025-09-12T034012.200.json

###

GET http://localhost:8080/api/uzytkownicy/whoami
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ3YmFwcCIsInN1YiI6Im5hdWN6eWNpZWxAbG9jYWwiLCJpYXQiOjE3NTc2NDExNzMsImV4cCI6MTc1NzY0MjA3MywidWlkIjoyLCJyb2xhIjoiTkFVQ1pZQ0lFTCIsInR5cFRva2VudSI6IkFDQ0VTUyJ9._At_sR-D0L0uc2CEhJRi2N6fGgXBvxCnSlzH2jCfmlc
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2025.1.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

<> 2025-09-12T034006.200.json

###

POST http://localhost:8080/api/auth/login
Content-Type: application/json
Content-Length: 57
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2025.1.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

{ "email": "nauczyciel@local", "haslo": "nauczyciel123" }

<> 2025-09-12T033933.200.json

###

GET http://localhost:8080/api/uzytkownicy/whoami
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ3YmFwcCIsInN1YiI6Im5hdWN6eWNpZWxAbG9jYWwiLCJpYXQiOjE3NTc2NDEwODMsImV4cCI6MTc1NzY0MTk4MywidWlkIjoyLCJyb2xhIjoiTkFVQ1pZQ0lFTCIsInR5cFRva2VudSI6IkFDQ0VTUyJ9.jpL3DZZbZd2KXh2Xrmv_TwQiDf9W9McsnGFmIr-2rng
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2025.1.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

<> 2025-09-12T033808.200.json

###

POST http://localhost:8080/api/auth/login
Content-Type: application/json
Content-Length: 57
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2025.1.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

{ "email": "nauczyciel@local", "haslo": "nauczyciel123" }

<> 2025-09-12T033803.200.json

###

POST http://localhost:8080/api/tablice
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ3YmFwcCIsInN1YiI6Im5hdWN6eWNpZWxAbG9jYWwiLCJpYXQiOjE3NTc2NDA3OTksImV4cCI6MTc1NzY0MTY5OSwidWlkIjoyLCJyb2xhIjoiTkFVQ1pZQ0lFTCIsInR5cFRva2VudSI6IkFDQ0VTUyJ9.aa3kK1pLd8utAyDLgIa_VV9SQhCSVgFl3S3u50acK5E
Content-Type: application/json
Content-Length: 50
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2025.1.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

{ "tytul": "Debug 1757640855", "wlascicielId": 2 }

<> 2025-09-12T033415.200.json

###

GET http://localhost:8080/api/tablice/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ3YmFwcCIsInN1YiI6Im5hdWN6eWNpZWxAbG9jYWwiLCJpYXQiOjE3NTc2NDA3OTksImV4cCI6MTc1NzY0MTY5OSwidWlkIjoyLCJyb2xhIjoiTkFVQ1pZQ0lFTCIsInR5cFRva2VudSI6IkFDQ0VTUyJ9.aa3kK1pLd8utAyDLgIa_VV9SQhCSVgFl3S3u50acK5E
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2025.1.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

<> 2025-09-12T033332.400.json

###

POST http://localhost:8080/api/tablice
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ3YmFwcCIsInN1YiI6Im5hdWN6eWNpZWxAbG9jYWwiLCJpYXQiOjE3NTc2NDA3OTksImV4cCI6MTc1NzY0MTY5OSwidWlkIjoyLCJyb2xhIjoiTkFVQ1pZQ0lFTCIsInR5cFRva2VudSI6IkFDQ0VTUyJ9.aa3kK1pLd8utAyDLgIa_VV9SQhCSVgFl3S3u50acK5E
Content-Type: application/json
Content-Length: 50
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2025.1.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

{ "tytul": "Debug 1757640805", "wlascicielId": 2 }

<> 2025-09-12T033325.200.json

###

GET http://localhost:8080/api/uzytkownicy/whoami
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ3YmFwcCIsInN1YiI6Im5hdWN6eWNpZWxAbG9jYWwiLCJpYXQiOjE3NTc2NDA3OTksImV4cCI6MTc1NzY0MTY5OSwidWlkIjoyLCJyb2xhIjoiTkFVQ1pZQ0lFTCIsInR5cFRva2VudSI6IkFDQ0VTUyJ9.aa3kK1pLd8utAyDLgIa_VV9SQhCSVgFl3S3u50acK5E
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2025.1.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

<> 2025-09-12T033322.200.json

###

POST http://localhost:8080/api/auth/login
Content-Type: application/json
Content-Length: 57
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2025.1.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

{ "email": "nauczyciel@local", "haslo": "nauczyciel123" }

<> 2025-09-12T033319.200.json

###

POST http://localhost:8080/api/tablice
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ3YmFwcCIsInN1YiI6Im5hdWN6eWNpZWxAbG9jYWwiLCJpYXQiOjE3NTc2NDA2NTUsImV4cCI6MTc1NzY0MTU1NSwidWlkIjoyLCJyb2xhIjoiTkFVQ1pZQ0lFTCIsInR5cFRva2VudSI6IkFDQ0VTUyJ9.xvC5YsSNlLffx_Q_NX2LDg_FXAnWDXGc4yWjY_2WdCo
Content-Type: application/json
Content-Length: 31
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2025.1.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

{ "tytul": "Debug 1757640659" }

<> 2025-09-12T033059.400.json

###

POST http://localhost:8080/api/auth/login
Content-Type: application/json
Content-Length: 57
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2025.1.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

{ "email": "nauczyciel@local", "haslo": "nauczyciel123" }

<> 2025-09-12T033055.200.json

###

POST http://localhost:8080/api/auth/login
Content-Type: application/json
Content-Length: 57
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2025.1.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

{ "email": "nauczyciel@local", "haslo": "nauczyciel123" }

<> 2025-09-12T032920.200.json

###

GET http://localhost:8080/api/tablice/1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ3YmFwcCIsInN1YiI6Im5hdWN6eWNpZWxAbG9jYWwiLCJpYXQiOjE3NTc2NDAxMzMsImV4cCI6MTc1NzY0MTAzMywidWlkIjoyLCJyb2xhIjoiTkFVQ1pZQ0lFTCIsInR5cFRva2VudSI6IkFDQ0VTUyJ9.T1Zm3M5Yh860-TPCKc6xWfGc4RGLAX1vxhAK_LAHqEE
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2025.1.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

<> 2025-09-12T032241.400.json

###

POST http://localhost:8080/api/tablice
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ3YmFwcCIsInN1YiI6Im5hdWN6eWNpZWxAbG9jYWwiLCJpYXQiOjE3NTc2NDAxMzMsImV4cCI6MTc1NzY0MTAzMywidWlkIjoyLCJyb2xhIjoiTkFVQ1pZQ0lFTCIsInR5cFRva2VudSI6IkFDQ0VTUyJ9.T1Zm3M5Yh860-TPCKc6xWfGc4RGLAX1vxhAK_LAHqEE
Content-Type: application/json
Content-Length: 59
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2025.1.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

{ "tytul": "Debug JWT", "opis": "Test", "wlascicielId": 2 }

<> 2025-09-12T032233.200.json

###

GET http://localhost:8080/api/uzytkownicy/whoami
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJ3YmFwcCIsInN1YiI6Im5hdWN6eWNpZWxAbG9jYWwiLCJpYXQiOjE3NTc2NDAxMzMsImV4cCI6MTc1NzY0MTAzMywidWlkIjoyLCJyb2xhIjoiTkFVQ1pZQ0lFTCIsInR5cFRva2VudSI6IkFDQ0VTUyJ9.T1Zm3M5Yh860-TPCKc6xWfGc4RGLAX1vxhAK_LAHqEE
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2025.1.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

<> 2025-09-12T032224.200.json

###

POST http://localhost:8080/api/auth/login
Content-Type: application/json
Content-Length: 57
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2025.1.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

{ "email": "nauczyciel@local", "haslo": "nauczyciel123" }

<> 2025-09-12T032213.200.json

###

POST http://localhost:8080/api/tablice
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YmFwcCIsInN1YiI6Im5hdWN6eWNpZWxAbG9jYWwiLCJpYXQiOjE3NTc2MzQ4NjMsImV4cCI6MTc1NzYzNTc2MywidWlkIjoyLCJyb2xhIjoiTkFVQ1pZQ0lFTCIsInR5cFRva2VudSI6IkFDQ0VTUyJ9.v63wiHGhcJCNLAkgMAFvJvHL3mGZUkPWBiRL1OuUzgQ
Content-Type: application/json
Content-Length: 59
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2025.1.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

{ "tytul": "Debug JWT", "opis": "Test", "wlascicielId": 2 }

###

POST http://localhost:8080/api/tablice
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YmFwcCIsInN1YiI6Im5hdWN6eWNpZWxAbG9jYWwiLCJpYXQiOjE3NTc2MzQ4NjMsImV4cCI6MTc1NzYzNTc2MywidWlkIjoyLCJyb2xhIjoiTkFVQ1pZQ0lFTCIsInR5cFRva2VudSI6IkFDQ0VTUyJ9.v63wiHGhcJCNLAkgMAFvJvHL3mGZUkPWBiRL1OuUzgQ
Content-Type: application/json
Content-Length: 59
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2025.1.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

{ "tytul": "Debug JWT", "opis": "Test", "wlascicielId": 2 }

###

POST http://localhost:8080/api/tablice
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YmFwcCIsInN1YiI6Im5hdWN6eWNpZWxAbG9jYWwiLCJpYXQiOjE3NTc2MzQ4NjMsImV4cCI6MTc1NzYzNTc2MywidWlkIjoyLCJyb2xhIjoiTkFVQ1pZQ0lFTCIsInR5cFRva2VudSI6IkFDQ0VTUyJ9.v63wiHGhcJCNLAkgMAFvJvHL3mGZUkPWBiRL1OuUzgQ
Content-Type: application/json
Content-Length: 59
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2025.1.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

{ "tytul": "Debug JWT", "opis": "Test", "wlascicielId": 2 }

###

GET http://localhost:8080/api/tablice/1/export?format=JSON&email=nauczyciel@local
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YmFwcCIsInN1YiI6Im5hdWN6eWNpZWxAbG9jYWwiLCJpYXQiOjE3NTc2MzQ4NjMsImV4cCI6MTc1NzYzNTc2MywidWlkIjoyLCJyb2xhIjoiTkFVQ1pZQ0lFTCIsInR5cFRva2VudSI6IkFDQ0VTUyJ9.v63wiHGhcJCNLAkgMAFvJvHL3mGZUkPWBiRL1OuUzgQ
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2025.1.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

<> 2025-09-12T015855.400.json

###

GET http://localhost:8080/api/tablice/1/eksport?format=JSON
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YmFwcCIsInN1YiI6Im5hdWN6eWNpZWxAbG9jYWwiLCJpYXQiOjE3NTc2MzQ4NjMsImV4cCI6MTc1NzYzNTc2MywidWlkIjoyLCJyb2xhIjoiTkFVQ1pZQ0lFTCIsInR5cFRva2VudSI6IkFDQ0VTUyJ9.v63wiHGhcJCNLAkgMAFvJvHL3mGZUkPWBiRL1OuUzgQ
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2025.1.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

<> 2025-09-12T015615.500.json

###

GET http://localhost:8080/api/tablice/1/export?format=JSON
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YmFwcCIsInN1YiI6Im5hdWN6eWNpZWxAbG9jYWwiLCJpYXQiOjE3NTc2MzQ4NjMsImV4cCI6MTc1NzYzNTc2MywidWlkIjoyLCJyb2xhIjoiTkFVQ1pZQ0lFTCIsInR5cFRva2VudSI6IkFDQ0VTUyJ9.v63wiHGhcJCNLAkgMAFvJvHL3mGZUkPWBiRL1OuUzgQ
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2025.1.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

<> 2025-09-12T015526.400.json

###

GET http://localhost:8080/api/tablice/1/eksport?format=JSON
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YmFwcCIsInN1YiI6Im5hdWN6eWNpZWxAbG9jYWwiLCJpYXQiOjE3NTc2MzQ4NjMsImV4cCI6MTc1NzYzNTc2MywidWlkIjoyLCJyb2xhIjoiTkFVQ1pZQ0lFTCIsInR5cFRva2VudSI6IkFDQ0VTUyJ9.v63wiHGhcJCNLAkgMAFvJvHL3mGZUkPWBiRL1OuUzgQ
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2025.1.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

<> 2025-09-12T015455.500.json

###

POST http://localhost:8080/api/tablice
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YmFwcCIsInN1YiI6Im5hdWN6eWNpZWxAbG9jYWwiLCJpYXQiOjE3NTc2MzQ4NjMsImV4cCI6MTc1NzYzNTc2MywidWlkIjoyLCJyb2xhIjoiTkFVQ1pZQ0lFTCIsInR5cFRva2VudSI6IkFDQ0VTUyJ9.v63wiHGhcJCNLAkgMAFvJvHL3mGZUkPWBiRL1OuUzgQ
Content-Type: application/json
Content-Length: 59
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2025.1.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

{ "tytul": "Debug JWT", "opis": "Test", "wlascicielId": 2 }

<> 2025-09-12T015432.200.json

###

GET http://localhost:8080/api/uzytkownicy/whoami
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YmFwcCIsInN1YiI6Im5hdWN6eWNpZWxAbG9jYWwiLCJpYXQiOjE3NTc2MzQ4NjMsImV4cCI6MTc1NzYzNTc2MywidWlkIjoyLCJyb2xhIjoiTkFVQ1pZQ0lFTCIsInR5cFRva2VudSI6IkFDQ0VTUyJ9.v63wiHGhcJCNLAkgMAFvJvHL3mGZUkPWBiRL1OuUzgQ
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2025.1.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

<> 2025-09-12T015429.200.json

###

GET http://localhost:8080/api/tablice
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YmFwcCIsInN1YiI6Im5hdWN6eWNpZWxAbG9jYWwiLCJpYXQiOjE3NTc2MzQ4NjMsImV4cCI6MTc1NzYzNTc2MywidWlkIjoyLCJyb2xhIjoiTkFVQ1pZQ0lFTCIsInR5cFRva2VudSI6IkFDQ0VTUyJ9.v63wiHGhcJCNLAkgMAFvJvHL3mGZUkPWBiRL1OuUzgQ
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2025.1.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*
content-length: 379

POST http://localhost:8080/api/tablice
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YmFwcCIsInN1YiI6Im5hdWN6eWNpZWxAbG9jYWwiLCJpYXQiOjE3NTc2MzQ4NjMsImV4cCI6MTc1NzYzNTc2MywidWlkIjoyLCJyb2xhIjoiTkFVQ1pZQ0lFTCIsInR5cFRva2VudSI6IkFDQ0VTUyJ9.v63wiHGhcJCNLAkgMAFvJvHL3mGZUkPWBiRL1OuUzgQ
Content-Type: application/json

{ "nazwa": "Debug JWT", "opis": "Test" }

<> 2025-09-12T015425.200.json

###

POST http://localhost:8080/api/auth/login
Content-Type: application/json
Content-Length: 57
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2025.1.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

{ "email": "nauczyciel@local", "haslo": "nauczyciel123" }

<> 2025-09-12T015423.200.json

###

GET http://localhost:8080/api/tablice/1/eksport?format=JSON
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YmFwcCIsInN1YiI6Im5hdWN6eWNpZWxAbG9jYWwiLCJpYXQiOjE3NTc2MzQ1NDcsImV4cCI6MTc1NzYzNTQ0NywidWlkIjoyLCJyb2xhIjoiTkFVQ1pZQ0lFTCIsInR5cFRva2VudSI6IkFDQ0VTUyJ9.n3GFKbEsZxkvU2N7zI_2lVtX9w-Tu6-rhKxaxhJbJbs
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2025.1.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

<> 2025-09-12T015402.500.json

###

GET http://localhost:8080/api/tablice/1/eksport?format=json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YmFwcCIsInN1YiI6Im5hdWN6eWNpZWxAbG9jYWwiLCJpYXQiOjE3NTc2MzQ1NDcsImV4cCI6MTc1NzYzNTQ0NywidWlkIjoyLCJyb2xhIjoiTkFVQ1pZQ0lFTCIsInR5cFRva2VudSI6IkFDQ0VTUyJ9.n3GFKbEsZxkvU2N7zI_2lVtX9w-Tu6-rhKxaxhJbJbs
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2025.1.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

<> 2025-09-12T014954.500.json

###

POST http://localhost:8080/api/tablice
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YmFwcCIsInN1YiI6Im5hdWN6eWNpZWxAbG9jYWwiLCJpYXQiOjE3NTc2MzQ1NDcsImV4cCI6MTc1NzYzNTQ0NywidWlkIjoyLCJyb2xhIjoiTkFVQ1pZQ0lFTCIsInR5cFRva2VudSI6IkFDQ0VTUyJ9.n3GFKbEsZxkvU2N7zI_2lVtX9w-Tu6-rhKxaxhJbJbs
Content-Type: application/json
Content-Length: 59
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2025.1.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

{ "tytul": "Debug JWT", "opis": "Test", "wlascicielId": 2 }

<> 2025-09-12T014941.200.json

###

GET http://localhost:8080/api/uzytkownicy/whoami
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YmFwcCIsInN1YiI6Im5hdWN6eWNpZWxAbG9jYWwiLCJpYXQiOjE3NTc2MzQ1NDcsImV4cCI6MTc1NzYzNTQ0NywidWlkIjoyLCJyb2xhIjoiTkFVQ1pZQ0lFTCIsInR5cFRva2VudSI6IkFDQ0VTUyJ9.n3GFKbEsZxkvU2N7zI_2lVtX9w-Tu6-rhKxaxhJbJbs
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2025.1.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

<> 2025-09-12T014921.200.json

###

GET http://localhost:8080/api/tablice
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YmFwcCIsInN1YiI6Im5hdWN6eWNpZWxAbG9jYWwiLCJpYXQiOjE3NTc2MzQ1NDcsImV4cCI6MTc1NzYzNTQ0NywidWlkIjoyLCJyb2xhIjoiTkFVQ1pZQ0lFTCIsInR5cFRva2VudSI6IkFDQ0VTUyJ9.n3GFKbEsZxkvU2N7zI_2lVtX9w-Tu6-rhKxaxhJbJbs
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2025.1.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*
content-length: 379

POST http://localhost:8080/api/tablice
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ3YmFwcCIsInN1YiI6Im5hdWN6eWNpZWxAbG9jYWwiLCJpYXQiOjE3NTc2MzQ1NDcsImV4cCI6MTc1NzYzNTQ0NywidWlkIjoyLCJyb2xhIjoiTkFVQ1pZQ0lFTCIsInR5cFRva2VudSI6IkFDQ0VTUyJ9.n3GFKbEsZxkvU2N7zI_2lVtX9w-Tu6-rhKxaxhJbJbs
Content-Type: application/json

{ "nazwa": "Debug JWT", "opis": "Test" }

<> 2025-09-12T014910.200.json

###

POST http://localhost:8080/api/auth/login
Content-Type: application/json
Content-Length: 57
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2025.1.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

{ "email": "nauczyciel@local", "haslo": "nauczyciel123" }

<> 2025-09-12T014907.200.json

###

