name: frontend

on:
  push:
    paths:
      - 'whiteboard-ui/**'
      - '.github/workflows/frontend.yml'
  pull_request:
    paths:
      - 'whiteboard-ui/**'
      - '.github/workflows/frontend.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: whiteboard-ui

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: whiteboard-ui/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Lint (optional)
        run: npm run lint --if-present

      - name: Build
        run: npm run build

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: whiteboard-ui-dist
          path: whiteboard-ui/dist
